title: Manuals
subtitle: ""
description: "Manuals for Jefferson Place"
# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

atom_feed:
  hide: true

footer:
